import type { ColumnType } from "kysely";
export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;
export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type AcademicInfo = {
    id: Generated<string>;
    scholar_id: string;
    course: string;
    year_level: number;
    section: string | null;
    is_regular: boolean;
    is_enrolled: boolean;
    semester_id: string;
    created_at: Generated<Timestamp | null>;
    updated_at: Timestamp | null;
    deleted_at: Timestamp | null;
};
export type AcademicInfoDuplicate = {
    id: Generated<string>;
    course: string;
    year_level: number;
    section: string | null;
    is_regular: boolean;
    is_enrolled: boolean;
    scholar_id: string;
    created_at: Generated<Timestamp | null>;
    updated_at: Timestamp | null;
    deleted_at: Timestamp | null;
};
export type Account = {
    id: Generated<string>;
    password: string;
    admin_id: string | null;
    coordinator_id: string | null;
    scholar_id: string | null;
    is_logged_in: Generated<boolean>;
    created_at: Generated<Timestamp | null>;
    updated_at: Timestamp | null;
    deleted_at: Timestamp | null;
};
export type Admin = {
    id: Generated<string>;
    first_name: string;
    last_name: string;
    birthdate: string | null;
    email: string;
    contact_number: string | null;
    role: Generated<string>;
    created_at: Generated<Timestamp | null>;
    updated_at: Timestamp | null;
};
export type AdminLogs = {
    id: Generated<string>;
    admin_id: string;
    action: string;
    description: string;
    status: Generated<string>;
    oldData: unknown | null;
    newData: unknown | null;
    created_at: Generated<Timestamp | null>;
    updated_at: Timestamp | null;
    deleted_at: Timestamp | null;
};
export type Campus = {
    id: Generated<string>;
    name: string;
    description: string | null;
    address: string;
    code: string | null;
    created_at: Generated<Timestamp | null>;
    updated_at: Timestamp | null;
    deleted_at: Timestamp | null;
};
export type Coordinator = {
    id: Generated<string>;
    first_name: string;
    middle_name: string | null;
    last_name: string;
    birthdate: string;
    email: string;
    contact_number: string;
    campus_id: string;
    role: Generated<string | null>;
    created_at: Generated<Timestamp | null>;
    updated_at: Timestamp | null;
    deleted_at: Timestamp | null;
};
export type CoordinatorLogs = {
    id: Generated<string>;
    coordinator_id: string;
    action: string;
    description: string;
    status: Generated<string>;
    oldData: unknown | null;
    newData: unknown | null;
    created_at: Generated<Timestamp | null>;
    updated_at: Timestamp | null;
    deleted_at: Timestamp | null;
};
export type Duty = {
    id: Generated<string>;
    name: string;
    acronym: string;
    description: string;
    required_hours: number;
    created_at: Generated<Timestamp | null>;
    updated_at: Timestamp | null;
    deleted_at: Timestamp | null;
};
export type DutyAssignment = {
    id: Generated<string>;
    scholar_id: string;
    duty_id: string;
    semester_id: string;
    created_at: Generated<Timestamp | null>;
    updated_at: Timestamp | null;
    deleted_at: Timestamp | null;
};
export type DutyRecord = {
    id: Generated<string>;
    scholar_id: string;
    schedule_id: string | null;
    semester_id: string;
    computed_hours: number;
    hours: string;
    minutes: string;
    type: Generated<string | null>;
    qr_code_id: string;
    status: Generated<string | null>;
    created_at: Generated<Timestamp | null>;
    updated_at: Timestamp | null;
    deleted_at: Timestamp | null;
};
export type DutySchedule = {
    id: Generated<string>;
    day: string;
    time_start: string;
    time_end: string;
    location: string;
    class_subject: string | null;
    class_type: string | null;
    class_level: string | null;
    department: string | null;
    max_slot: string | null;
    duty_id: string;
    campus_id: string;
    semester_id: string;
    created_at: Generated<Timestamp | null>;
    updated_at: Timestamp | null;
    deleted_at: Timestamp | null;
    is_visible_to_scholar: Generated<boolean>;
};
export type DutyScheduleAssignment = {
    id: Generated<string>;
    schedule_id: string;
    scholar_id: string;
    semester_id: string;
    assignment_status: Generated<string>;
    created_at: Generated<Timestamp | null>;
    updated_at: Timestamp | null;
    deleted_at: Timestamp | null;
};
export type HkInfo = {
    id: Generated<string>;
    hk_number: string | null;
    hk_type: string;
    year_starter: number;
    scholar_id: string;
    campus_id: string;
    created_at: Generated<Timestamp | null>;
    updated_at: Timestamp | null;
    deleted_at: Timestamp | null;
};
export type QrCode = {
    id: Generated<string>;
    qr_holder_id: string;
    code: string;
    expiration_date: Timestamp | null;
    type: Generated<string | null>;
    hours: number | null;
    minutes: number | null;
    purpose: string | null;
    location: string | null;
    date_time: Timestamp | null;
    created_at: Generated<Timestamp | null>;
    updated_at: Timestamp | null;
    deleted_at: Timestamp | null;
};
export type QrHolder = {
    id: Generated<string>;
    first_name: string;
    middle_name: string | null;
    last_name: string;
    department: string;
    email: string;
    contact_number: string;
    role: Generated<string | null>;
    created_at: Generated<Timestamp | null>;
    updated_at: Timestamp | null;
    deleted_at: Timestamp | null;
};
export type Scholar = {
    id: Generated<string>;
    first_name: string;
    middle_name: string | null;
    last_name: string | null;
    student_number: string;
    email: string;
    contact_number: string;
    address: string;
    birthdate: string;
    created_at: Generated<Timestamp | null>;
    updated_at: Timestamp | null;
    deleted_at: Timestamp | null;
    role: Generated<string | null>;
};
export type ScholarGuardian = {
    id: Generated<string>;
    guardian_fname: string;
    guardian_lname: string;
    contact_num: string;
    email: string;
    scholar_id: string;
    created_at: Generated<Timestamp | null>;
    updated_at: Timestamp | null;
    deleted_at: Timestamp | null;
};
export type ScholarLogs = {
    id: Generated<string>;
    scholar_id: string;
    action: string;
    description: string;
    status: Generated<string>;
    oldData: unknown | null;
    newData: unknown | null;
    created_at: Generated<Timestamp | null>;
    updated_at: Timestamp | null;
    deleted_at: Timestamp | null;
};
export type Semester = {
    id: Generated<string>;
    term: string;
    sy: string;
    status: Generated<string | null>;
    created_at: Generated<Timestamp | null>;
    updated_at: Timestamp | null;
    deleted_at: Timestamp | null;
};
export type TrustedDevice = {
    id: Generated<number>;
    account_id: string;
    name: string | null;
    code: string | null;
    created_at: Generated<Timestamp | null>;
    updated_at: Timestamp | null;
    deleted_at: Timestamp | null;
};
export type DB = {
    academic_info: AcademicInfo;
    academic_info_duplicate: AcademicInfoDuplicate;
    account: Account;
    admin: Admin;
    admin_logs: AdminLogs;
    campus: Campus;
    coordinator: Coordinator;
    coordinator_logs: CoordinatorLogs;
    duty: Duty;
    duty_assignment: DutyAssignment;
    duty_record: DutyRecord;
    duty_schedule: DutySchedule;
    duty_schedule_assignment: DutyScheduleAssignment;
    hk_info: HkInfo;
    qr_code: QrCode;
    qr_holder: QrHolder;
    scholar: Scholar;
    scholar_guardian: ScholarGuardian;
    scholar_logs: ScholarLogs;
    semester: Semester;
    trusted_device: TrustedDevice;
};
